insert into company.place_object (street, number, local, post_code, city, country) values ('Thierer', 1, 1, '411 45', 'Mukařov', 'Czech Republic');
insert into company.place_object (street, number, local, post_code, city, country) values ('Bowman', 2, 2, null, 'Tarrafal', 'Cape Verde');
insert into company.place_object (street, number, local, post_code, city, country) values ('Rieder', 3, 3, '58884-000', 'Catolé do Rocha', 'Brazil');
insert into company.place_object (street, number, local, post_code, city, country) values ('Gerald', 4, 4, '93285', 'Saint-Denis', 'France');
insert into company.place_object (street, number, local, post_code, city, country) values ('Morning', 5, 5, null, 'Andros Town', 'Bahamas');
insert into company.place_object (street, number, local, post_code, city, country) values ('Orin', 6, 6, '57351', 'Kamālia', 'Pakistan');
insert into company.place_object (street, number, local, post_code, city, country) values ('Stone Corner', 7, 7, '50770', 'Ārifwāla', 'Pakistan');
insert into company.place_object (street, number, local, post_code, city, country) values ('Scott', 8, 8, '97701', 'Ranua', 'Finland');
insert into company.place_object (street, number, local, post_code, city, country) values ('Erie', 9, 9, null, 'Dārayyā', 'Syria');
insert into company.place_object (street, number, local, post_code, city, country) values ('Tomscot', 10, 10, null, 'San Antonio del Monte', 'El Salvador');
